[#221686427] Added new stage for deploying client SDK to NPM
pagopa/io-functions-bpd pull request #6
Opened 2021-02-05 10:26 UTC by gquadrati

2021-02-09 09:16 UTC, balanza submitted a review, later dismissed

2021-02-09 11:02 UTC, balanza requested changes
Please review the package name

2021-02-09 11:04 UTC, gquadrati commented
> Please review the package name

I didn't noticed!!

2021-02-09 11:09 UTC, gquadrati commented
> Please review the package name

Done in [e847302](https://github.com/pagopa/io-functions-bpd/pull/6/commits/e847302ff8a74c39cdaf93bd36de7b38c5475d7e)

2021-02-09 11:29 UTC, balanza approved these changes, later dismissed

2021-02-18 14:57 UTC, balanza approved these changes

2021-02-18 14:58 UTC, merged